sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install coveralls
  - git worktree add ./ci-test ci-test

script:
  - cd ci-test
  - sh ./scripts/runs.sh

after_success:
  - coveralls
