sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.3" ]; then pip install enum34 typing fi
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.4" ]; then pip install typing fi
  - pip install coverage coveralls

script:
  - mypy .
  - py.test --cov

after_success:
  - coverage report
  - coveralls
