sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install pytest --upgrade
  - pip install coveralls
  - pip install -qr test/requirements-test.txt

script:
  - pytest

after_success:
  - coveralls
