sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install pytest --upgrade
  - pip install neovim
  - pip install mypy-lang flake8 coverage pytest-flake8 pytest-cov
  - if [[ "$TRAVIS_PYTHON_VERSION" = "3.3" ]]; then pip install enum34 typing; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" = "3.4" ]]; then pip install typing; fi
  - pip install coveralls

script:
  - py.test --cov
  - mypy --silent-imports rplugin/python3

after_success:
  - coveralls
